### PR TITLE
Add battery status screen.

### PR DESCRIPTION
**Pull request by kzaragoza**
- Refactor handleKeys to rollerHandleKeys to clarify usage now that we have multiple modal keyboard handlers.
- Add a new screen to display a battery graphic and text percentage on pressing the 'b' key from the roller page.

### CODE REVIEW

**Comment by LispEngineer** [comment]
@kzaragoza Can you please update your PR with the merged changes from Jared? Thanks

**Comment by LispEngineer** [comment]
@kzaragoza This will also need to go to v1.0 :)

**Comment by kzaragoza** [comment]
So you stuck me with the merge? Sheesh!

Merged and updated to 1.0.

**Review by LispEngineer — APPROVED** [review]
LGTM, Approved

**Pull request merged**
